---

- name: Check for NGINX folders
  stat:
   path: "{{item}}"
  register: folder_stats
  with_items:
  - ["/etc/nginx/sites-enabled/","/etc/nginx/sites-available/"]

- name: Creat NGINX folders if not existend
  file:
   path: "{{item.item}}"
   state: directory
   mode: 0644
   group: root
   owner: root
  when: item.stat.exists == false
  with_items:
  - "{{folder_stats.results}}"

- name: Add Site Config to sites-available/
  template:
    src: reverseproxy.conf.j2
    dest: /etc/nginx/sites-available/{{ item.key }}.conf
    owner: root
    group: root
  with_dict: "{{ nginx_revproxy_sites }}"

- name: Enable Site Config in sites-enabled/
  file:
    src: /etc/nginx/sites-available/{{ item.key }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.key }}
    state: link
  with_dict: "{{ nginx_revproxy_sites }}"

- name: Check for site folder
  stat:
   path: "/var/www/{{ item.key }}"
  register: folder_stats_site
  with_dict: "{{ nginx_revproxy_sites }}"

- name: Creat site folder if not existend
  file:
   path: "{{ item.item }}"
   state: directory
   mode: 0755
   group: www-data
   owner: www-data
  when: item.stat.exists == false
  with_items:
  - "{{folder_stats_site.results}}"
