---
# Defines tasks applicable for NTP (Network Time Protocol)

- name: Install NTP
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_enabled: true
    ntp_manage_config: true
    ntp_timezone: Europe/Berlin
    ntp_servers:
      - "ntp1.hetzner.de  iburst"
      - "ntp2.hetzner.com iburst"
      - "ntp3.hetzner.net iburst"
